### ISSUE TITLE
Support "Elgato Ring Light"

### ISSUE THREAD

**Issue by Multisaft7** [derjayjay/homebridge-keylights#117]
Hey,

is it possible also to use the new "Elgato Ring Light"?

**Comment by derjayjay** [comment]
Hi,

Yeah, the ring light should work, all Elgato lights seem to use the same API.

I don't have access to Ring Light though; so please feel free to test and let me know if there are any issues.

**Comment by Multisaft7** [comment]
Ok, will check! But do I need to configure something in the Settings!? 
However, I have no idea how to add the light ... because I can't make sense of the instructions!

**Comment by derjayjay** [comment]
No, nothing needs to be configured in the settings.

It's really simple to set up. First, you follow the instructions provided with the lights to connect them to your network. After that, all you have to do is to install the plugin to your Homebridge and restart the server. The lights are automatically detected by the plugin and configured.

**Comment by Multisaft7** [comment]
Ok, after the restart it works like a charm :-) Maybe you can also add the ring light to the readme

**Comment by derjayjay** [comment]
Happy to hear :)

Yes, I will update the readme.
