### ISSUE TITLE
After plugin and HOOBS reinstall, Plugin can't control the lights

### ISSUE THREAD

**Issue by mariusstrom** [derjayjay/homebridge-keylights#7]
I had an unfortunate situation (note to self: never upgrade node just for the heck of it) that required a complete in-place reinstall of HOOBS and all plugins. Upon reinstalling, the Keylight plugin picked up the cached accessory for my Keylight, however, it's unable to control the Keylight at all.

Any suggestions on how to completely blow away the cached settings for the plugin so it can start re-discovery from scratch?

```
12/1/2020, 9:10:42 AM [Elgato Key Lights] Loading accessory from cache: Elgato Key Light 6F41
12/1/2020, 9:10:43 AM [Elgato Key Lights] Discovered accessory on network: Elgato Key Light 6F41
12/1/2020, 9:10:51 AM [Elgato Key Lights] Restoring existing accessory from cache: Elgato Key Light 6F41 as Elgato Key Light 6F41
```

**Comment by derjayjay** [comment]
Well, with standard Homebridge, you would just delete the accessories from the cache folders. 

With HOOBS, look for Menu -> Help -> Reset Connections should help.

**Comment by mariusstrom** [comment]
Got it, thanks. I found that before it was actually controlling the keylight - but just lagging by about 45-60 seconds 👎 

I ended up deleting `.hoobs/etc/accessories/cachedAccessories` and was able to rediscover and rapidly control the keylight at that point. (unfortunately had the side effect of burning the objectIDs of several of my hoobs-controlled devices, but c'est la vie)
