### ISSUE TITLE
Multiple Keylights - how to config?

### ISSUE THREAD

**Issue by mvondemhagen** [derjayjay/homebridge-keylights#79]
How do I configure more than one Keylight?

**Comment by derjayjay** [comment]
Hi there,

the lights are automatically discovered on the network and dynamically added to homebridge, there is nothing special you have to do. :)

**Comment by mvondemhagen** [comment]
I see! Initially, discovery seemed not to work, so I played with adding the section twice with IP address as name. My fault, works like a charm, thanks!
